import { listBlogs, listJobs, listPortfolio } from '../lib/content';

/**
 * Sitemap generation.
 *
 * `public/sitemap.xml` was a static file with 22 hardcoded URLs and `lastmod`
 * dates frozen at whenever it was last generated by hand. It listed no blog
 * post, no job and no case study — and it also omitted seven pages that are
 * live, indexable and worth ranking (`/domain/`, `/domain/ecommerce/`,
 * `/domain/events/`, `/domain/hotel/`, `/domain/travel-and-hospitality/`,
 * `/services/e-commerce-development/`, `/services/software-testing-qa-services/`).
 *
 * Two deliberate choices:
 *
 * 1. **Static pages carry no `lastmod`.** The old file claimed dates it could
 *    not know, and a build-time timestamp would be worse: every page would
 *    claim to change on every deploy. `lastmod` is optional, and a crawler that
 *    catches a site lying about it discounts the signal everywhere. Only
 *    database-backed URLs get one, because only they have a real edit date.
 * 2. **A DB failure degrades, it does not 500.** A sitemap that errors is worse
 *    than a sitemap missing its dynamic half, so each query is independently
 *    tolerant and the static routes always ship.
 */

export type ChangeFreq = 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';

export interface SitemapEntry {
  /** Site-relative, with the trailing slash `next.config.mjs` enforces. */
  path: string;
  /** ISO 8601. Omitted unless we know a real modification date. */
  lastmod?: string;
  changefreq?: ChangeFreq;
  priority?: number;
}

/**
 * Every static route we advertise.
 *
 * Deliberately absent:
 *  - `/get-offer/` — a bare lead-capture form: one heading and four fields, 80
 *    characters of text. It stays crawlable and reachable from campaigns, but
 *    thin pages listed in a sitemap dilute the quality signal for everything
 *    around them. Add it back once the page has content worth ranking.
 *  - `/get-offer/specialoffers/` — noindex; the URL carries applicant PII.
 *  - `/404` — not a destination.
 */
export const STATIC_ROUTES: SitemapEntry[] = [
  { path: '/', changefreq: 'weekly', priority: 1.0 },

  { path: '/about-us/', changefreq: 'monthly', priority: 0.8 },
  { path: '/culture/', changefreq: 'monthly', priority: 0.6 },
  { path: '/contact-us/', changefreq: 'monthly', priority: 0.8 },

  { path: '/services/', changefreq: 'monthly', priority: 0.9 },
  { path: '/services/custom-software-development/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/it-staff-augmentation/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/web-development/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/mobile-app-development/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/mvp-development/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/ai-ml/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/cloud-computing-solutions/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/digital-marketing-services/', changefreq: 'monthly', priority: 0.8 },
  // Both of these are live, indexable and were missing from the old sitemap.
  { path: '/services/e-commerce-development/', changefreq: 'monthly', priority: 0.8 },
  { path: '/services/software-testing-qa-services/', changefreq: 'monthly', priority: 0.8 },

  { path: '/domain/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/fintech/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/healthcare/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/oil-and-gas/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/food-and-beverages/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/ecommerce/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/events/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/hotel/', changefreq: 'monthly', priority: 0.7 },
  { path: '/domain/travel-and-hospitality/', changefreq: 'monthly', priority: 0.7 },

  { path: '/blog/', changefreq: 'daily', priority: 0.7 },
  { path: '/career/', changefreq: 'daily', priority: 0.7 },
  { path: '/portfolio/', changefreq: 'weekly', priority: 0.7 },
];

/** The five characters that are not legal as raw text inside an XML element. */
export const escapeXml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

const toIso = (value: unknown): string | undefined => {
  if (typeof value !== 'string' && !(value instanceof Date)) return undefined;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? undefined : date.toISOString();
};

/** Slugs and ids reach the URL, so anything path-unsafe disqualifies the row. */
const isUsableSegment = (value: unknown): value is string | number => {
  if (typeof value === 'number') return Number.isFinite(value);
  return typeof value === 'string' && value.trim().length > 0 && !/[/\s?#]/.test(value);
};

export const renderUrlset = (entries: SitemapEntry[], baseUrl: string): string => {
  const urls = entries
    .map((entry) => {
      const loc = escapeXml(new URL(entry.path, baseUrl).toString());
      const parts = [`    <loc>${loc}</loc>`];
      if (entry.lastmod) parts.push(`    <lastmod>${entry.lastmod}</lastmod>`);
      if (entry.changefreq) parts.push(`    <changefreq>${entry.changefreq}</changefreq>`);
      if (entry.priority !== undefined) {
        parts.push(`    <priority>${entry.priority.toFixed(1)}</priority>`);
      }
      return `  <url>\n${parts.join('\n')}\n  </url>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
};

export const renderSitemapIndex = (paths: string[], baseUrl: string): string => {
  const maps = paths
    .map((path) => {
      const loc = escapeXml(new URL(path, baseUrl).toString());
      return `  <sitemap>\n    <loc>${loc}</loc>\n  </sitemap>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${maps}
</sitemapindex>
`;
};

// ---------------------------------------------------------------------------
// Database-backed entries
//
// These go through the same content seam the pages use, so a sitemap can never
// advertise URLs from one store while the pages render from the other. Each
// settles independently and swallows its own failure: an empty urlset is a
// valid sitemap, a 500 is not.
// ---------------------------------------------------------------------------

const safely = async <T,>(load: () => Promise<T[]>): Promise<T[]> => {
  try {
    return await load();
  } catch {
    return [];
  }
};

export const blogEntries = async (): Promise<SitemapEntry[]> =>
  (await safely(listBlogs))
    .filter((row) => isUsableSegment(row.slug))
    .map((row) => ({
      path: `/blog/${row.slug}/`,
      lastmod: toIso(row.updated_at) ?? toIso(row.created_at),
      changefreq: 'monthly' as const,
      priority: 0.6,
    }));

export const jobEntries = async (): Promise<SitemapEntry[]> =>
  (await safely(listJobs))
    .filter((row) => isUsableSegment(row.id))
    .map((row) => ({
      path: `/career/${row.id}/`,
      lastmod: toIso(row.updated_at) ?? toIso(row.created_at),
      // Postings open and close; this is the one collection that genuinely
      // changes week to week.
      changefreq: 'weekly' as const,
      priority: 0.7,
    }));

export const portfolioEntries = async (): Promise<SitemapEntry[]> =>
  (await safely(listPortfolio))
    .filter((row) => isUsableSegment(row.id))
    .map((row) => ({
      path: `/portfolio/${row.id}/`,
      lastmod: undefined,
      changefreq: 'monthly' as const,
      priority: 0.6,
    }));

/**
 * Absolute base for `<loc>` values.
 *
 * `NEXT_PUBLIC_SITE_URL` is authoritative when set — a sitemap must agree with
 * the canonical host or it advertises a second origin for every page. Only when
 * it is absent do we fall back to the request's own host, which keeps preview
 * deployments and local runs self-consistent.
 */
export const resolveBaseUrl = (req?: {
  headers: Record<string, string | string[] | undefined>;
}): string => {
  const configured = process.env.NEXT_PUBLIC_SITE_URL?.trim();
  if (configured) return configured.replace(/\/$/, '');

  const header = (name: string): string | undefined => {
    const value = req?.headers?.[name];
    return Array.isArray(value) ? value[0] : value;
  };

  const host = header('x-forwarded-host') ?? header('host');
  if (host) {
    const proto = header('x-forwarded-proto') ?? (host.startsWith('localhost') ? 'http' : 'https');
    return `${proto}://${host}`;
  }

  return 'http://localhost:3000';
};

/** Shared by every XML route: same headers, same 200. */
export const XML_HEADERS = {
  'Content-Type': 'application/xml; charset=utf-8',
  // Sitemaps are cheap to regenerate and expensive to serve stale.
  'Cache-Control': 'public, max-age=0, s-maxage=3600, stale-while-revalidate=86400',
} as const;
