import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-postgres';

/**
 * Adds `users.role`.
 *
 * Generated by `migrate:create`, then split by hand. Both edits are the ones
 * docs/CONTENT-SOURCE.md warns recur on every generated migration, plus one
 * specific to this change:
 *
 *  1. **The unused `payload` and `req` parameters were removed.** `tsconfig`
 *     sets `noUnusedParameters`, so the generated signature is a type error,
 *     not a lint warning: `next build` fails with `'payload' is declared but
 *     its value is never read`.
 *  2. **The single `ADD COLUMN ... NOT NULL` was split into three steps.** See
 *     below — this is the one that would have taken the deploy down.
 *
 * No `CREATE SCHEMA` is needed here, unlike the initial migration: `payload`
 * already exists by the time this runs, because migration 1 created it.
 *
 * What was generated:
 *
 *   ALTER TABLE "payload"."users" ADD COLUMN "role" "payload"."enum_users_role" NOT NULL;
 *
 * `role` is `required: true` on the collection, so Payload emits NOT NULL in
 * the same statement that adds the column. On an empty table that works. On a
 * populated one Postgres has to put something in the new column for every
 * existing row, there is no default, and it fails outright:
 *
 *   ERROR: column "role" of relation "users" contains null values
 *
 * The whole migration then rolls back — so the one statement becomes the three
 * it actually needs to be: add nullable, backfill, then constrain. That is the
 * standard shape for adding a required column to a live table.
 *
 * The database this runs against holds real data (~6,955 applied_jobs rows,
 * 2,875 resumes) and the only backup is schema-only, so nothing below drops,
 * truncates or rewrites anything. The single UPDATE touches one column, on rows
 * where it is currently NULL.
 *
 * Payload runs each migration inside a transaction, so every `throw` here
 * aborts cleanly, leaving the table exactly as it was.
 */

/**
 * The account that must end up holding `admin`.
 *
 * Named explicitly rather than "whoever has the lowest id", because the lowest
 * id is whatever happened to be created first — as likely a throwaway test
 * account as a person. Granting admin to the wrong row is not a recoverable
 * mistake in a migration.
 */
const ADMIN_EMAIL = 'piyush@nextlooptechnologies.com';

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // 1. The enum, and the column — NULLABLE for now. Adding a nullable column
  //    with no default is a catalogue-only change in Postgres 11+: no table
  //    rewrite, and no lock held while every row is copied.
  await db.execute(sql`
   CREATE TYPE "payload"."enum_users_role" AS ENUM('admin', 'marketing', 'sales', 'hr');
  ALTER TABLE "payload"."users" ADD COLUMN "role" "payload"."enum_users_role";`);

  // 2. Backfill the one account that has to be an admin.
  const promoted = await db.execute(sql`
    UPDATE "payload"."users"
       SET "role" = 'admin'
     WHERE lower("email") = lower(${ADMIN_EMAIL})
       AND "role" IS NULL;
  `);

  /**
   * If that matched nothing, stop.
   *
   * Carrying on would apply NOT NULL to a table with no admin in it — an
   * installation where nobody can create users, assign roles or reach the
   * leads, and which cannot be repaired from inside the panel because every
   * route to doing so is itself admin-only. Failing the deploy is the cheaper
   * outcome by a wide margin.
   *
   * Falsy rather than `=== 0`: pg types rowCount as `number | null`, and a null
   * would slip past an equality check and carry on to SET NOT NULL.
   */
  if (!promoted.rowCount) {
    throw new Error(
      `add_user_roles: no user with email ${ADMIN_EMAIL} exists in payload.users, so there is ` +
        'nobody to make an admin. Aborting rather than leaving the panel with no administrator. ' +
        'Check the address, or create that account first, then re-run.'
    );
  }

  /**
   * Any other pre-existing account is a deliberate decision, not a default.
   *
   * NOT NULL cannot be applied while other rows are NULL, so something has to
   * fill them — but every value in this enum grants real access to real data,
   * and `hr` on a forgotten test account is a door into 2,875 candidate CVs.
   * There is no "no permissions" role to fall back on, so this refuses to
   * guess, and names exactly what needs deciding.
   */
  const leftover = await db.execute(sql`
    SELECT "id", "email" FROM "payload"."users" WHERE "role" IS NULL ORDER BY "id";
  `);

  if (leftover.rows.length > 0) {
    const listed = leftover.rows
      .map(
        (r: Record<string, unknown>) => `${String(r.id)} <${String(r.email)}>`
      )
      .join(', ');
    throw new Error(
      `add_user_roles: ${leftover.rows.length} other user account(s) have no role: ${listed}. ` +
        'Every role in this enum grants access to live data, so this migration will not pick one ' +
        'for you. Either delete the accounts that are no longer needed, or add an explicit UPDATE ' +
        'for each one above this check, then re-run.'
    );
  }

  // 3. Every row now has a value, so the constraint can go on. This is what
  //    makes the database agree with `required: true` on the field — and it is
  //    the state the committed .json snapshot describes, so leaving it off
  //    would make the next generated migration try to add it again.
  await db.execute(sql`
   ALTER TABLE "payload"."users" ALTER COLUMN "role" SET NOT NULL;`);
}

/**
 * As generated, plus IF EXISTS on both statements.
 *
 * `up` can abort part-way at either guard above. That rolls back, so in
 * practice `down` never meets a half-applied column — but a `down` that only
 * works against a perfectly-applied `up` is the kind of thing you find out
 * about while trying to recover from something else.
 *
 * No user data is lost: `role` did not exist before this migration.
 */
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload"."users" DROP COLUMN IF EXISTS "role";
  DROP TYPE IF EXISTS "payload"."enum_users_role";`);
}
